# The Liebmann’s method

### Using Liebmann’s method to solve for the temperature of the square heated plate

In [2]:
import numpy as np

# Liebmann method function (Gauss-Seidel with overrelaxation)

def liebmann_method(temperature, omega, epsilon_s=1, max_iterations=10000, track_iterations=[]):
    max_error = 1e10
    rows, cols = temperature.shape
    rows -= 2
    cols -= 2
    iteration = 0
    temperature_iterations = [] 

    while max_error > epsilon_s and iteration < max_iterations:
        max_error = 0
        for i in range(1, rows + 1):
            for j in range(1, cols + 1):
                T_old = temperature[i, j]
                T_new = 0.25 * (temperature[i + 1][j] + temperature[i - 1][j] + temperature[i][j + 1] + temperature[i][j - 1])
                temperature[i, j] = omega * T_new + (1 - omega) * T_old
                max_error = max(max_error, abs(temperature[i, j] - T_old))
        iteration += 1
        if iteration in track_iterations:
            temperature_iterations.append((iteration, temperature.copy()))

    return temperature, iteration, temperature_iterations

# Updating the boundary conditions and initializing the temperature grid

temperature_grid = np.array([
    [150.0, 150.0, 150.0, 150.0, 150.0],
    [50.0, 0.0, 0.0, 0.0, 50.0],
    [50.0, 0.0, 0.0, 0.0, 50.0],
    [50.0, 0.0, 0.0, 0.0, 50.0],
    [0.0, 0.0, 0.0, 0.0, 0.0]
])

# Overrelaxation factor

omega = 1.2

# Solving for the interior temperatures using the modified Liebmann method

solved_temperature, iterations_needed, temperature_iterations = liebmann_method(temperature_grid, omega, track_iterations=list(range(1, 7)))

# getting the interior readings of the temperature

T_interior = solved_temperature[1:-1, 1:-1]

# printing the iterations as well as the temperature values

print("Final Solution:")
labels = ['T13', 'T23', 'T33', 'T12', 'T22', 'T32', 'T11', 'T21', 'T31']
for label, value in zip(labels, T_interior.flatten()):
    print(f"{label} = {value:.5f}")

print("\nNumber of Iterations:", iterations_needed)

# Printing the solved temperature grid in matrix form for the final solution

print("\nSolved Temperature Grid:")
for row in solved_temperature:
    print(row)

# Printing the values of all 6 iterations

for iteration, temp_grid in temperature_iterations:
    print(f"\nIteration {iteration}:")
    for row in temp_grid:
        print(row)

Final Solution:
T13 = 89.27444
T23 = 97.77341
T33 = 89.28743
T12 = 59.38522
T22 = 62.51137
T32 = 59.37767
T11 = 35.71994
T21 = 33.48618
T31 = 35.71449

Number of Iterations: 6

Solved Temperature Grid:
[150. 150. 150. 150. 150.]
[50.         89.27444261 97.77340786 89.28743083 50.        ]
[50.         59.38521926 62.51137376 59.3776669  50.        ]
[50.         35.71994293 33.48617825 35.71449072 50.        ]
[0. 0. 0. 0. 0.]

Iteration 1:
[150. 150. 150. 150. 150.]
[50.  60.  63.  78.9 50. ]
[50.   33.   28.8  47.31 50.  ]
[50.    24.9   16.11  34.026 50.   ]
[0. 0. 0. 0. 0.]

Iteration 2:
[150. 150. 150. 150. 150.]
[50.    76.8   87.75  84.738 50.   ]
[50.    47.55  53.856 57.324 50.   ]
[50.     29.118  31.878  34.9554 50.    ]
[0. 0. 0. 0. 0.]

Iteration 3:
[150. 150. 150. 150. 150.]
[50.      85.23    94.5972  88.62876 50.     ]
[50.       55.9512   61.15392  58.956624 50.      ]
[50.        35.52516   33.114744  35.6303304 50.       ]
[0. 0. 0. 0. 0.]

Iteration 4:
[150. 150. 1